### ISSUE TITLE
The "e" in the Unconference is running away. Maybe we can use a smaller font.

### ISSUE THREAD

**Issue by melissawm** [numfocus/disc-unconference-2025#3]
The "e" in the Unconference is running away. Maybe we can use a smaller font.
![Screenshot_20240912_134936_Firefox Focus](https://github.com/user-attachments/assets/c0e1a1ad-5e60-4335-af74-ef7f3f3637c1)

_Originally posted by @kamila-NF in https://github.com/numfocus/disc-unconference-2025/issues/2#issuecomment-2347230289_

**Comment by Ramya-Shah** [comment]
Hi, I would like to take up this issue.

**Comment by anmolgupta2015** [comment]
Hii, Kindly check my pull request it resolves the issue.

**Comment by red-panda3** [comment]
hii, I would like to resolve the issue

**Comment by melissawm** [comment]
Resolved by #5
